#!/bin/bash

# Path to the extlinux.conf file generated by Buildroot
EXTLINUX_CONF="$TARGET_DIR/boot/extlinux/extlinux.conf"

# Line to append
OVERLAY_LINE="  FDTOVERLAYS /boot/overlays/testoverlay.dtbo"

# Check if the line already exists to prevent duplication
grep -q "$OVERLAY_LINE" "$EXTLINUX_CONF"
if [ $? -eq 0 ]; then
    echo "The overlay line already exists in $EXTLINUX_CONF"
    exit 0
fi

# Append the overlay line after "devicetreedir /boot"
awk -v insert="$OVERLAY_LINE" '/devicetreedir \/boot/ { print; print insert; next }1' "$EXTLINUX_CONF" > /tmp/extlinux.conf

# Replace the original file with the new file
mv /tmp/extlinux.conf "$EXTLINUX_CONF"

echo "The overlay line has been added to $EXTLINUX_CONF"