name: image-build
on:
    push:
        branches:
            - main
            - 9-add-auto-build-on-new-commits-to-master-using-github-actions

jobs:
    build:
        runs-on: self-hosted
        timeout-minutes: 480
        steps:
            - uses: actions/checkout@v2
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - name: Build Linux image
              env:
                BR_PROJECT_WIFI_SSID: ${{ secrets.BR_PROJECT_WIFI_SSID }}
                BR_PROJECT_WIFI_PASSWORD: ${{ secrets.BR_PROJECT_WIFI_PASSWORD }}
              run: |
                ./clean-build.sh